### ISSUE TITLE
Couldn't find smpl_vt_ft.pkl file

### ISSUE THREAD

**Issue by divyaYK** [minar09/MGN-Py3#3]
Hey @minar09 

I couldn't find smpl_vt_ft.pkl which causes problem with smpl_paths.py file...
Could you please attach that file?

**Comment by minar09** [comment]
Hi, sorry I forgot to add the assets folder. Please check now. Thanks.

**Comment by divyaYK** [comment]
Thanks for uploading @minar09!
But I still couldn't run the visualize_garments.py file and got the following error:
```python visualize_garments.py 
Traceback (most recent call last):
  File "visualize_garments.py", line 66, in <module>
    vt, ft = dp.get_vt_ft_hres()
  File "/home/divya/MGN-Py3/utils/smpl_paths.py", line 84, in get_vt_ft_hres
    vt, ft = SmplPaths.get_vt_ft()
  File "/home/divya/MGN-Py3/utils/smpl_paths.py", line 79, in get_vt_ft
    vt, ft = pkl.load(open(smpl_vt_ft_path))
TypeError: a bytes-like object is required, not 'str'
```
Could you please let me know how I can rid of this error?

**Comment by minar09** [comment]
This is a kind of OS related issue, probably the .pkl files were saved in another OS. I uploaded another folder named "assets-win", which contains the fixed .pkl files with surname "_unix.pkl". You can either directly use those files or convert from the original ones using the `assets-win/dos2unix.py` script.

**Comment by divyaYK** [comment]
I've been using ubuntu 20.04 through virtualbox.
I'm getting the same error again. 
I tried giving 'rb' mode for the smpl_vt_ft.pkl file, but I got another error:
```bash
Traceback (most recent call last):
  File "visualize_garments.py", line 66, in <module>
    vt, ft = dp.get_vt_ft_hres()
  File "/home/divya/MGN-Py3/utils/smpl_paths.py", line 84, in get_vt_ft_hres
    vt, ft = SmplPaths.get_vt_ft()
  File "/home/divya/MGN-Py3/utils/smpl_paths.py", line 79, in get_vt_ft
    vt, ft = pkl.load(open(smpl_vt_ft_path, 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 0: ordinal not in range(128)
```

**Comment by minar09** [comment]
I think there are fixes available for this error. Please search for your specific issues. For instance: https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/

**Comment by divyaYK** [comment]
Thanks, that worked!! 
I hate to disturb you but here's another one: 
```bash
Traceback (most recent call last):
  File "visualize_garments.py", line 67, in <module>
    smpl = Smpl(dp.get_hres_smpl_model_data())
  File "/home/divya/MGN-Py3/utils/smpl_paths.py", line 44, in get_hres_smpl_model_data
    backwards_compatibility_replacements(dd)
  File "/home/divya/MGN-Py3/lib/serialization.py", line 41, in backwards_compatibility_replacements
    dd['J'] = dd['joints']
KeyError: 'joints'
```

**Comment by minar09** [comment]
Maybe the key is already deleted or not present. You can put a try-exception block or comment-out the code actually, I guess its not that critical. Or you can find the available keys from the dictionary as well to modify the code 
`for key, value in dd.items():
    # do something with keys and values`

**Comment by divyaYK** [comment]
Alright, I commented it. 

I have this error:
```bash
Traceback (most recent call last):
  File "visualize_garments.py", line 67, in <module>
    smpl = Smpl(dp.get_hres_smpl_model_data())
  File "/home/divya/MGN-Py3/utils/smpl_paths.py", line 48, in get_hres_smpl_model_data
    num_betas = dd[b'shapedirs'].shape[-1]
  File "/home/divya/anaconda3/envs/tf1/lib/python3.6/site-packages/chumpy/ch.py", line 317, in shape
    return self.r.shape
  File "/home/divya/anaconda3/envs/tf1/lib/python3.6/site-packages/chumpy/ch.py", line 594, in r
    self._call_on_changed()
  File "/home/divya/anaconda3/envs/tf1/lib/python3.6/site-packages/chumpy/ch.py", line 588, in _call_on_changed
    if len(self._dirty_vars) > 0:
AttributeError: 'Ch' object has no attribute '_dirty_vars
```
I'm assuming this is probably because of bytes encoding I had to use to read dd from smplify file.

**Comment by minar09** [comment]
If Chumpy installed with pip generating error, then you may try installing from the repository directly (https://github.com/mattloper/chumpy) or maybe installing from a specific commit.

**Comment by Void-Mohit** [comment]
**you can try this way to load the model don't need to go for the assets-win folder.**

>vert_indices, fts = pkl.load(open(fts_file,'rb'),encoding='latin1')

**Comment by divyaYK** [comment]
@Void-Mohit Thanks! I'll try that.
